server:
  port: 8083

spring:
  application:
    name: service-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false
    feign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-8083
    prefer-ip-address: true
consumer:
  message: "这是修改后的服务消费者消息 - 时间戳：[当前时间]"